version: "3"
services:
  mongo:
    image: mongo
    container_name: mongo_mongoose
    volumes:
      - .:/usr/src/code
    restart: always
    ports:
        - 27018:27017
    environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: root!p4sswd
      MONGO_INITDB_DATABASE: nodemongoose

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root!p4sswd